<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>Kairo.Core</RootNamespace>
    </PropertyGroup>

    <!-- AOT compatible -->
    <PropertyGroup>
        <IsAotCompatible>true</IsAotCompatible>
    </PropertyGroup>

    <!-- 界面文本：Localization/Languages/<语言代码>.json -->
    <ItemGroup>
        <EmbeddedResource Include="Localization/Languages/*.json" LogicalName="Kairo.Core.Lang.%(Filename).json" />
    </ItemGroup>
</Project>
