name: Build

on:
  push:
    paths:
      - "**.cs"
  pull_request:
  workflow_dispatch:

jobs:
  BuildForWindows:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Write Build info
        shell: cmd
        run: |
          cmd /c echo GITHUB ACTION #${{github.run_number}} >${{ github.workspace }}\Kairo\buildinfo.info
          cmd /c echo %date% %time% >>${{ github.workspace }}\Kairo\buildinfo.info
          cmd /c echo ${{github.ref}} ${{github.sha}}>>${{ github.workspace }}\Kairo\buildinfo.info

      - name: DotNet restore
        run: dotnet restore
      
      - name: Build the Updater(Publish,SC,Single File)
        run: |
          dotnet clean
          dotnet publish "Updater/Updater.csproj" -f net9.0-windows -r win-x64 -p:PublishSingleFile=true -p:RuntimeIdentifier=win-x64 -p:IncludeContentInSingleFile=true -p:Configuration=Release --sc -p:IncludeAllContentForSelfExtract=true -p:EnableCompressionInSingleFile=true
          
      - name: Build the project(Publish,Single File)
        run: |
          dotnet clean
          dotnet publish "Kairo/Kairo.csproj" -f net9.0-windows -r win-x64 -p:PublishSingleFile=true -p:RuntimeIdentifier=win-x64 -p:IncludeContentInSingleFile=true -p:Configuration=Release --sc -p:IncludeAllContentForSelfExtract=true -p:EnableCompressionInSingleFile=true

      - name: Upload Kairo(Publish,Single File)
        uses: actions/upload-artifact@v4
        with:
          name: Kairo_dotnet9_publish_SingleFile
          path: ${{ github.workspace }}\Kairo\bin\Release\net9.0-windows\win-x64\publish
          if-no-files-found: ignore

  
